### ISSUE TITLE
Webcam

### ISSUE THREAD

**Issue by drdink2012** [beyhangl/People-Counting-by-zones#1]
Hi, thanks for sharing this great work. Is it possible to use own webcam as input?

**Comment by beyhangl** [comment]
Hey,

Sure you need to change this line
cv2.VideoCapture(input_video_file)

To 

cv2.VideoCapture(0)

**Comment by drdink2012** [comment]
Thanks beyhangl :)

**Comment by Anislar** [comment]
flag, frame =cam.read()
                          ^
TabError: inconsistent use of tabs and spaces in indentation 
sorry i have error in this line

**Comment by beyhangl** [comment]
closed
